### ISSUE TITLE
Changing Font Colors

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#10]
How can we change the font colors on all the website pages (titles, posts, etc.)?

Ross

**Comment by ahafeez7** [comment]
I am not sure if color hasn't been incorporated in the markdown for github yet. 

Nevertheless, you can enclose your text starting and ending within three backticks and it will appear like this:

```
//your text
```

Also, if you have code written in javascript, css, html, python etc, that can be highlighted in its own style. More information can be found at markdown cheatsheet:https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
Search for code and syntax highlighting.

**Comment by ahmetcecen** [comment]
There is no way to assign individual colors to text within a page using markdown. The best option available is to change title or body text colors for the entire website. That is somewhat messy at the moment, and requires editing of clean-blog.css with a line similar to:

``` css
 h1,
 .h1 {
   font-size: 36px;
   color: #00ff00;
 }
```

where the color code can be picked from http://www.w3schools.com/tags/ref_colorpicker.asp.

We will at some point include an easier way to customize the color theme.

An alternative solution is to use html tags to alter color within a post with something like this:

``` html
<p><font color="red">Your Text Here</font></p>
```

The good news is you can do this fairly easily inside a markdown file, bad news is you can't do this for the presentation layout. 

We will also at some point, create a sample post that uses simple html tags to alter basic formatiing not supported by markdown like color, that you can use as a cheat sheet and copy paste from.
