### ISSUE TITLE
Adding Methods and Results Tags to Posts for Differentiation

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#12]
Is it possible to add query tags to each post that specify whether its a post about Methods or Results?

Maybe this would best to have two separate pages for each?  We can discuss this further about the best way to proceed.

Ross

**Comment by ahmetcecen** [comment]
This is fairly easy to do. I will implement this on your project as a test, then pull to the main project-pages as a permanent addition. Give me a some time though since it is a busy time at the moment.
