### ISSUE TITLE
Animations in Webpage 

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#14]
Can we find a way to include either interactive pictures or animations in the website?

Obviously there is a space limitation to this but I am sure using this functionality a couple times on the website can be really useful.

Ross

**Comment by ahafeez7** [comment]
I am not sure about any specific animations but you can use youtube videos, with an image pointing to the actual video. You find the example at the very end of the following link.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#youtube-videos

Replacing YOUTUBE_VIDEO_ID_HERE with g81KMQjyOUM results in a sample NRM video as follows:

[NMR sample video]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=g81KMQjyOUM
" target="_blank"><img src="http://img.youtube.com/vi/g81KMQjyOUM/0.jpg" alt="NMR Spectroscopy demo" width="240" height="180" border="10" /></a>

**Comment by ahmetcecen** [comment]
This needs further details. Elaborate on what you would like to achieve with the animation, and that will help us narrow down your options.
