### ISSUE TITLE
How to Change Picture Sizes?  What pixel count to use?

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#15]
How can we specify picture dimensions on the website?

When we create figures, what pixel count should I make them with so that they do not appear blurry?

Ross and Krishna

**Comment by tonyfast** [comment]
Send a link to an example please.

**Comment by RossVerploegh** [comment]
For example, the main picture on this webpage.

http://rossverploegh.github.io/Hybrid-ZIF-Structure-Elucidation/

I want to know what the largest pixel count I need to have picture look good on a computer screen (arbitrary dimensions).

Furthermore, I want to understand how the picture is being cropped when posted.
https://github.com/RossVerploegh/Hybrid-ZIF-Structure-Elucidation/blob/gh-pages/img/ZIF-8_window.jpg

**Comment by tonyfast** [comment]
I would suggest going off and searching the web.  A lot of the questions that you are asking are common across the web.  A little primer in some HTML, Javascript, and some CSS would be a good place to start.  Basically the rule of thumb is to look at StackOverflow.com results first.  The Open source community is fantastic there.

Don't host images on Github.  It is not meant for that, the performance of your website will suffer considerably.  Github is meant to main text based documents that can fit into a revision control model. 

Images are enormous strings that would pollute and weigh down your revision history.  I would suggest using a photo hosting service like Flickr.  I share a lot of [my scientific data](flickr.com/photos/tonyfast/) there.  You get 1 TB for free.

**Comment by ahmetcecen** [comment]
The main page picture is a completely different question. That has a pre-arranged formatting and has specific resolution requirements, which I will get to the bottom of when I have time. 

However in general for a post, it is fairly easy to modify the size of an image through stretch and shrinking like you would in a ppt. Here instead you have to input explicit pixels values, and you can decide on what you want after a couple trial and error iterations. I will look into alternate ways of doing this, but for now use the following as a guideline:

http://stackoverflow.com/a/22486140

**Comment by ahmetcecen** [comment]
Addressed at ppguide.
