### ISSUE TITLE
Indenting Text in Markdown

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#16]
How do you indent text lines in markdown?

Krishna and Ross

**Comment by tonyfast** [comment]
Can you show an example in the issue?

**Comment by RossVerploegh** [comment]
If I have 2 lines and I want them to be centered on the page, how to do that?

Example:

Georgia Institute
of Technology

**Comment by RossVerploegh** [comment]
Georgia Institute
                                                                              of Technology

That's a better example.

**Comment by RossVerploegh** [comment]
They are obviously not centered in the previous post....

**Comment by tonyfast** [comment]
Markdown does not do that per se.

Markdown is a plain-text readable syntax that can be converted to HTML.  The goal of markdown is that it structure is legible in plain-text emails and can be converted to web pages.  Once you have the Markdown HTML then you can use CSS3 styling to center the HTML elements.

**Comment by ahmetcecen** [comment]
I have heard that there is a way to add alignment properties to markdown using css callouts. I will look into this later on. For now you can use inline html using the guideline:

http://www.w3schools.com/tags/att_p_align.asp
