### ISSUE TITLE
Do Not Fork!

### ISSUE THREAD

**Issue by ahmetcecen** [projectpages/project-pages#22]
Settle on a way for users to deploy project-pages without forking.

**Comment by tonyfast** [comment]
Why don't you want to fork?

Otherwise bower, git clone, or git archive are the simplest uptake on a project like this.

**Comment by ahmetcecen** [comment]
Forking should be reserved for people developing Project-Pages. If "users" fork the repository, they cannot create a second project page in the same account. The new roundabout method will ensure the fork relationship doesn't exist.

http://matin-hub.github.io/ppguide/

http://matin-hub.github.io/ppguide/installation
