### ISSUE TITLE
More flexible tags

### ISSUE THREAD

**Issue by latmarat** [projectpages/project-pages#33]
Can you make tags more flexible so that

1) each post may have multiple tags,
2) tags are arbitrary text keywords rather than images from a predefined list (methods / results)?

See, for example, Notepad theme ([demo](http://www.hossainmohdfaysal.com/Notepad/), [repo](https://github.com/hmfaysal/Notepad)), which has text tags, categories and their indexes.

**Comment by ahmetcecen** [comment]
Posts can already have multiple tags, simply separate them by a coma.

I will look into implementing the second one, the demo looks nice.
