### ISSUE TITLE
Salvage and Utilize D3.js content submitted by @ewang5

### ISSUE THREAD

**Issue by ahmetcecen** [projectpages/project-pages#59]

**Comment by tonyfast** [comment]
I would suggest looking into some higher level javascript charting libraries like highcharts, c3, bokeh, or vega.  In fact, vega lite will get you really far and it possible that you can build that into the front matter.

**Comment by ahmetcecen** [comment]
The libs you mentioned definitely look handy, I will check them out for future templates.

On the other hand, I am getting convinced more and more that building a front matter hot-swapped template is a poor way to solve the visualization problem. Instead I am creating Python and MATLAB connectors that spit out a fully formatted visualization instance. Imagine Make3DStructure.m creating the entire markdown/html file with the data in your work space already embedded inside: http://ahmetcecen.github.io/ply-threejs/.

**Comment by ahmetcecen** [comment]
Content not easily salvageable, buggy and incomplete. The branch is deleted and stored in a backup location, and is postponed indefinitely.
