### ISSUE TITLE
css not rendering after upload to s3

### ISSUE THREAD

**Issue by robbyki** [projectpages/project-pages#89]
Really love and have been looking for exactly this theme and trying to get the base up and running to start publishing some content but running into issues with the page rendering correctly after uploading to s3. Works perfectly when using a --serve flag and testing but after I upload all of the files from _site the css is not working and there is some broken link somewhere. Pretty new to html/css so would appreciate any guidance for how to pinpoint the issue. Thank you.

**Comment by ahmetcecen** [comment]
Can you explain to me in a bit more detail how you are setting up? I will probably need to recreate it to pinpoint the problem.

**Comment by ahmetcecen** [comment]
Actually, even better is if you can use a debugging tool on the broken webpage and print out the error (like Chrome F12) or give me a link to the broken page if it is online.

**Comment by robbyki** [comment]
Thanks so much. Here is the page: http://mysitetest2.s3-website-us-east-1.amazonaws.com/
Basically, I just cloned the repo and am using ruby 2.4 with jekyll 3.3 and works perfectly when serving locally.

**Comment by ahmetcecen** [comment]
It says: 

http://10.239.197.103:4000/css/bootstrap.min.css Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

Meaning you have written either `localhost` or `10.239.197.103:4000` in the **url** or **baseurl** options in _config.yml. You need to change that to: `http://mysitetest2.s3-website-us-east-1.amazonaws.com`.

When you do this, the site will no longer work for your local machine, but it will work on S3.

Let me know if this solves the problem.

**Comment by robbyki** [comment]
Thanks a lot.
