### ISSUE TITLE
Pictures from GitHub repo url not loading

### ISSUE THREAD

**Issue by RossVerploegh** [projectpages/project-pages#9]
The picture shows up on this link:
https://github.com/RossVerploegh/Hybrid-ZIF-Structure-Elucidation/blob/gh-pages/_posts/2015-02-27-EMMCZ-RJV.markdown

The picture does not appear here:
http://rossverploegh.github.io/Hybrid-ZIF-Structure-Elucidation/2015/02/27/EMMCZ-RJV/

**Comment by ahmetcecen** [comment]
Fixed on the post.
