### ISSUE TITLE
Cloudflare free SSL breaks page layout

### ISSUE THREAD

**Issue by CRASCanada** [projectpages/project-pages#92]
Hi there,

I'm still fairly new to Jekyll and coding so apologies in advance if this question sounds stupid.
I'm hosting my domain on Cloudflare and everything works perfect through HTTP. However if I enable the free SSL on Cloudflare (Flexible or Full), the page would still load but the layout is all messed up.

Any tips on how to troubleshoot this is greatly appreciated. Thank you!

**Comment by ahmetcecen** [comment]
I only test the code against GitHub deployment, so I may have made an assumption somewhere that doesn't necessarily hold true for Cloudflare. Can you F12 on the deployed page on Chrome and go to the console (or open the equivalent of console on another browser) and see what errors are displayed when on a broken page?

**Comment by CRASCanada** [comment]
Thanks for your quick reply.
Error messages in Chrome console:

> Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/clean-blog.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/syntax.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/colorscheme.css'. This request has been blocked; the content must be served over HTTPS.
cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML:32 WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
replaceScript @ cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML:32
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure script 'http://crascanada.org/js/clean-blog.min.js'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/clean-blog.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/colorscheme.css'. This request has been blocked; the content must be served over HTTPS.
crascanada.org/:1 Mixed Content: The page at 'https://crascanada.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://crascanada.org/css/syntax.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by ahmetcecen** [comment]
Sounds like you didn't put https on the url section in config yaml, make sure it is:

url: "https://crascanada.org/"

Let me know if this fixes it.

**Comment by CRASCanada** [comment]
Ah I initially set the URL as crascanada.github.io and forgot to update it.
Yes problem solved. Thanks very much sir. Have a god day:)
