### ISSUE TITLE
Recently by the same author not working

### ISSUE THREAD

**Issue by devinharia** [projectpages/project-pages#93]
Hi!

I see a code of Recently by the same author in post.html, but it isn't working. I've placed two posts of different titles with the same author, yet nothing is coming up. I tried placing that piece of code within "article" tags, yet nothing comes up. Do I have to place it somewhere else? Any help would be highly appreciated.

Thanks!

**Comment by ahmetcecen** [comment]
It only shows up on a big screen. I didn't want to clutter the screen if the user didn't have loads of space. I think it was something around 1400 pixels. You can emulate this by zooming out artificially in the browser. In chrome that would be Ctrl + Mouse Scroll.

Admittedly there are some short-sighted design decisions in this functionality. Will keep this in mind if I do another improvement round any time soon.

**Comment by devinharia** [comment]
Oh got it! Thanks a lot for such a quick reply!
